[build]
  publish = "asuogov-deployment"
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules for clean URLs
[[redirects]]
  from = "/meet-the-directors/"
  to = "/meet-the-directors.html"
  status = 301

[[redirects]]
  from = "/our-directors/"
  to = "/our-directors.html"
  status = 301

[[redirects]]
  from = "/sges/"
  to = "/sges.html"
  status = 301

[[redirects]]
  from = "/passed-resolutions/"
  to = "/passed-resolutions.html"
  status = 301
